codecov:
  require_ci_to_pass: yes

coverage:

    status:

        project:

            default:
                target: null
                threshold: 2%

        patch:
          default:
            enabled: no
